### ISSUE TITLE
The demo page doesn't return anything

### ISSUE THREAD

**Issue by precogtyrant** [vsuthichai/paraphraser#3]
Hello,
I just tried using the demo at http://pair-a-phrase.it/
I tried testing with a sentence but it didn't return any result. 

The http request shows it failed. 

thanks

**Comment by vsuthichai** [comment]
Hi @precogtyrant, apologies the model is served off a home gpu, which isn't very cost effective for me.  I'm looking for a *cheap* gpu host provider.

**Comment by precogtyrant** [comment]
Hi @vsuthichai thanks for your reply.
I tried running the inference.py but I got an error on the file embeddings.py (line 9) where it tries to open the "../../para-nmt-50m/data/ngram-word-concat-40.pickle" which isn't in the directory. Where can I find the file? Also, is it necessary to load it when I am just trying to use the pretrained models included in the project?

thanks again

**Comment by vsuthichai** [comment]
you cand it here https://drive.google.com/file/d/1l2liCZqWX3EfYpzv9OmVatJAEISPFihW/view?usp=sharing
